# Generated by Django 3.1.3 on 2020-11-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=440)),
                ('type', models.CharField(choices=[('Fundacja', 'Fund'), ('Organizacja pozarządowoa', 'Org'), ('Zbiórka lokalna', 'Zbl')], default='Fundacja', max_length=26)),
                ('category_of_items', models.ManyToManyField(to='pages.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=126)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=55)),
                ('zip_code', models.CharField(max_length=6)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=250)),
                ('categories_of_items', models.ManyToManyField(to='pages.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.institution')),
            ],
        ),
    ]
